// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAau9gnhklSDPQXo9J6gzVgdy9QecyUUGc',
    appId: '1:1048843462577:web:008b48c1af0f1e0612ff90',
    messagingSenderId: '1048843462577',
    projectId: 'e-commerce-8161f',
    authDomain: 'e-commerce-8161f.firebaseapp.com',
    storageBucket: 'e-commerce-8161f.appspot.com',
    measurementId: 'G-LEP4D1HZNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8TYyP-myQcR7zPUSPlatgmG-ZXmSUFP0',
    appId: '1:1048843462577:android:afcd879f748e7b2e12ff90',
    messagingSenderId: '1048843462577',
    projectId: 'e-commerce-8161f',
    storageBucket: 'e-commerce-8161f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXF4o1Fq4A6XZNxagNQzcenk-DLoP8iW4',
    appId: '1:1048843462577:ios:b6599f872a4025ea12ff90',
    messagingSenderId: '1048843462577',
    projectId: 'e-commerce-8161f',
    storageBucket: 'e-commerce-8161f.appspot.com',
    androidClientId: '1048843462577-2omcddi1ku3kg19q0d5u9bhao1bdg64q.apps.googleusercontent.com',
    iosClientId: '1048843462577-3573tcb86e41q9r09i5ak3u614v9vb94.apps.googleusercontent.com',
    iosBundleId: 'com.example.cncPrac',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXF4o1Fq4A6XZNxagNQzcenk-DLoP8iW4',
    appId: '1:1048843462577:ios:b6599f872a4025ea12ff90',
    messagingSenderId: '1048843462577',
    projectId: 'e-commerce-8161f',
    storageBucket: 'e-commerce-8161f.appspot.com',
    androidClientId: '1048843462577-2omcddi1ku3kg19q0d5u9bhao1bdg64q.apps.googleusercontent.com',
    iosClientId: '1048843462577-3573tcb86e41q9r09i5ak3u614v9vb94.apps.googleusercontent.com',
    iosBundleId: 'com.example.cncPrac',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAau9gnhklSDPQXo9J6gzVgdy9QecyUUGc',
    appId: '1:1048843462577:web:c01668bbdad7ae2a12ff90',
    messagingSenderId: '1048843462577',
    projectId: 'e-commerce-8161f',
    authDomain: 'e-commerce-8161f.firebaseapp.com',
    storageBucket: 'e-commerce-8161f.appspot.com',
    measurementId: 'G-X5ECBGSP7Z',
  );
}
